### PR TITLE
Fix/mobileview

### PR DESCRIPTION
**Pull request by adityapandey23**
Issue Number = https://github.com/himeshparashar/Social-Morph/issues/7
The following issues have been resolved: #7 

Navbar: Collapsing and toggle menu functionality restored.
Infocard: Mobile mode display corrected.
Testimonial Section: Optimized for mobile mode, now displaying only one card.
Footer: Content structuring enhanced for better organization.
Important Notes

The features in the navbar require separate attention and have not been modified at this time.
The landing page button design has been adjusted to resolve display issues affecting other elements; further refinement can be addressed separately.

### CODE REVIEW

**Comment by adityapandey23** [comment]
@himeshparashar @Shobhit-Nagpal 
I have made the new branch and also can you guys please add the labels for gssoc-ext and hacktober fest, it'll really help me a lot!
Thanks in advance !
(Will start working on the docker issues which has been assigned to me asap)

**Comment by adityapandey23** [comment]
Hey thanks for merging can you add the tags as well ?
@himeshparashar @Shobhit-Nagpal

**Comment by Shobhit-Nagpal** [comment]
@himeshparashar we also would need to assign the gssoc-ext and level tag on the original issue and the PR

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal do you have access to asign labels ? If so please you can also do that

**Comment by Shobhit-Nagpal** [comment]
@himeshparashar yeah, just checked. i'll add labels from further issues. i'll just confirm the level label with you once

**Pull request merged**
