### PR TITLE
#45 Unusual ui alignment

### PR DESCRIPTION
**Pull request by CharVaibhav**
1. Modified Infocards component to highlight key features (unlimited accounts, brands, and posts) with SVG icons.

2. Fixed alignment issues to ensure the card stays centered on all screen sizes (desktop, tablet, mobile).

3. Applied a purple gradient background with shadows for a clean look.

4. Tested across devices to ensure everything looks good.
Screenshot 2024-10-17 192156

### CODE REVIEW

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal review needed

**Comment by Shobhit-Nagpal** [comment]
on it. will review by eod

**Review by Shobhit-Nagpal — COMMENTED** [review]
@himeshparashar lgtm

**Comment by himeshparashar** [comment]
@CharVaibhav if you can resolve the conflict else I will take time to resolve and merge

**Comment by CharVaibhav** [comment]
I have solved it

**Review by himeshparashar — APPROVED** [review]
@CharVaibhav thanks 👍

**Pull request merged**
