### PR TITLE
#83 Add Frontend for Signup/Signin

### LINKED ISSUE #83: Get Started button functionality
I have seen the issue already been raised but no-one seem to be working on it so , i want to propose making a signup/signin page when the Get started button is clicked.

i would request @himeshparashar to close that original issue that has been open from 2 weeks and assign me it with level3 and appropriate labels,, i will 100% do it:)

### PR DESCRIPTION
**Pull request by Siddhi-sahu**
Hey @himeshparashar,

This PR closes #83.

As mentioned in issue #83, I'm only working on the frontend. I have created the Signup and Signin pages, as requested. Clicking on "Get started" will now navigate to the signup route.

I didn't integrate the backend since it's not expected, and I'm not familiar with Redis

image

image

## Screen Recording
Here's a demo of the feature in action:
https://youtu.be/VXzahCUY-ec

### CODE REVIEW

**Comment by Siddhi-sahu** [comment]
@himeshparashar, could you please review the changes?

**Review by himeshparashar — CHANGES_REQUESTED** [review]
@Siddhi-sahu the background looks odd 
and the layout I have mentioned in the issue ref was like form and image side by side

**Comment by himeshparashar** [comment]
@Siddhi-sahu expected layout 
image

**Comment by Siddhi-sahu** [comment]
do you have like an image or something to go on the other side? or do you would like a quote there and can replace it with a image later on @himeshparashar

**Comment by himeshparashar** [comment]
For now you can use any free stock image from internet, will change it later

**Comment by Siddhi-sahu** [comment]
image
heyy @himeshparashar this color looks good to you or i should go with the purple gradient color from the landing page?

**Comment by himeshparashar** [comment]
> image heyy @himeshparashar this color looks good to you or i should go with the purple gradient color from the landing page?

try with purple gradient also if that looks good and attach a ss 
else its good to go for me 👍

**Comment by Siddhi-sahu** [comment]
@himeshparashar it would look something like this with the gradient

image

so how do you prefer it?

**Comment by Siddhi-sahu** [comment]
@himeshparashar i also found an image so i added that too

**Comment by Siddhi-sahu** [comment]
@himeshparashar oh you merged it, sorry but the changes wasnt finished. I didnt add the gradient to the signin.

**Comment by himeshparashar** [comment]
> @himeshparashar oh you merged it, sorry but the changes wasnt finished. I didnt add the gradient to the signin.

just add new commit for the remaining changes

**Pull request merged**
