### PR TITLE
resolved accordion bug added logo

### LINKED ISSUE #41: UI issues
1. dropdown not rendering below features.
2. get started not working
3. none of the navbar button are redirecting
4. logo is not appropriate, I can make a better logo
5. all the arrow start t point down when one dropdown is opened

image

image
I can work on all these issues collectively under a level3
context: gssoc gssoc-ext hacktoberfest hacktoberfest-accepted

### PR DESCRIPTION
**Pull request by ShivanshPlays**
closes #41 

Added logo 
log

and resolved the accordion bug of all chevrons going up when only one was opened
Screenshot 2024-10-06 184726

rest pages weren't available these are all I could solve.

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
Hi, tell me what changes you need,

**Review by himeshparashar — CHANGES_REQUESTED** [review]
Don't add logo I have got the logo https://github.com/himeshparashar/Social-Morph/pull/62

else lgtm

**Comment by ShivanshPlays** [comment]
okay I'll modify accordingly

**Comment by ShivanshPlays** [comment]
Hi

> Don't add logo I have got the logo #62
> 
> else lgtm

Removed logo, please check @himeshparashar

**Pull request merged**
