### PR TITLE
Added the the pricing Page with proper linking in the navbar wiht sleek ui.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the the pricing Page with proper linking in the navbar wiht sleek ui.

issue closes :- #13 

https://github.com/user-attachments/assets/15f271d6-7f89-44ea-b6b0-98752149a10c

https://github.com/user-attachments/assets/e83ccd7a-69d8-4bfc-936a-ac0749e6a6a6

@himeshparashar Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. I think it can be level 3 because i have added a new page to the website with linking it to the navbar for easy access and also it is responsive for all the screen sizes so provide me points based on my hard work on this.

### CODE REVIEW

**Review by himeshparashar — CHANGES_REQUESTED** [review]
image

can you make the CTA button on the pricing page something similar to in this image 
like the placement of button above the details and the button be a square with soft rounded corner instead of circular sides that you have build

else other looks great!

**Comment by tarunkumar2005** [comment]
@himeshparashar I have updated it you can check now.

**Comment by tarunkumar2005** [comment]
Please put it level 3 because of my efforts in this.

**Review by himeshparashar — APPROVED** [review]
looks great

**Comment by himeshparashar** [comment]
> Please put it level 3 because of my efforts in this.

That's for sure, a lot of effort has gone into this. I can't assign it as a level 3 because level 3 issues involve both frontend and backend.

**Comment by tarunkumar2005** [comment]
> > Please put it level 3 because of my efforts in this.
> 
> That's for sure, a lot of effort has gone into this. I can't assign it as a level 3 because level 3 issues involve both frontend and backend.

Okay its your choice, but thanks for recognising my efforts in this.

**Pull request merged**
