### PR TITLE
Added:: Missing Meta Tags for SEO Enhancement

### PR DESCRIPTION
**Pull request by myselfshivams**
Issue #11

### CODE REVIEW

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal  please review the code and also check that the changes are on another branch and the code doesn't break

**Comment by Shobhit-Nagpal** [comment]
> @Shobhit-Nagpal please review the code and also check that the changes are on another branch and the code doesn't break

sure thing. on it

**Comment by Shobhit-Nagpal** [comment]
@myselfshivams also, do make the changes on a separate branch and not the master branch :))

**Comment by himeshparashar** [comment]
@myselfshivams please look at the suggestion by @Shobhit-Nagpal

**Comment by myselfshivams** [comment]
> @myselfshivams please look at the suggestion by @Shobhit-Nagpal

Okay, I will make the changes as @Shobhit-Nagpal suggested.

**Pull request merged**
