### PR TITLE
Fixed the issues related to mobile responsiveness

### PR DESCRIPTION
**Pull request by adityapandey23**
Issue Number  = #7 
The following issues have been resolved:

- Navbar: Collapsing and toggle menu functionality restored.
- Infocard: Mobile mode display corrected.
- Testimonial Section: Optimized for mobile mode, now displaying only one card.
- Footer: Content structuring enhanced for better organization.

Important Notes

- The features in the navbar require separate attention and have not been modified at this time.
- The landing page button design has been adjusted to resolve display issues affecting other elements; further refinement can be addressed separately.

Here is the demo :

https://github.com/user-attachments/assets/f2fe7aa8-50de-48c5-9072-2c6e6ea9418a

### CODE REVIEW

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal  review needed

**Comment by adityapandey23** [comment]
Hey guys!
Can I have an update?
(PS: I want to start working on another issue related to docker in the repo and until this is pending I can't start working on it..Can you do the needful)

**Comment by Shobhit-Nagpal** [comment]
Hey @adityapandey23 , yess. I'll just have a look at it. Sorry for any delay

**Review by Shobhit-Nagpal — COMMENTED** [review]
code itself looks good to me. it's better to send in a PR from a separate branch and not the master branch @adityapandey23  (i see you're a fellow linux user btw)

other than that, lgtm @himeshparashar

**Comment by himeshparashar** [comment]
@adityapandey23 please create a new branch for the changes

**Comment by adityapandey23** [comment]
@Shobhit-Nagpal 
Okay I'll create another PR from a separate branch
and yes hehe Linux user

**Comment by adityapandey23** [comment]
@himeshparashar @Shobhit-Nagpal Is it okay if I choose dev over here ?
image

**Comment by Shobhit-Nagpal** [comment]
> @himeshparashar @Shobhit-Nagpal Is it okay if I choose dev over here ? image

no. you'd need to choose the master branch on the original repository but choose the fix branch on your forked repository.

the master branch is where the main changes will occur so that's why we would choose master branch

**Comment by adityapandey23** [comment]
Okay @himeshparashar @Shobhit-Nagpal 
I have created the new pr we can close this PR

**Comment by Shobhit-Nagpal** [comment]
awesome. @himeshparashar let me know how you want to go about closing and merging PRs. do you want me to handle them or you'll merge them on your end after the review?

**Pull request closed without merging**
