### PR TITLE
Added:: Missing Meta Tags for SEO Enhancement

### PR DESCRIPTION
**Pull request by myselfshivams**
This PR resolves Issue #11
I’ve made the necessary adjustments

### CODE REVIEW

**Comment by himeshparashar** [comment]
@myselfshivams in future please use new branch for creating PR's don't disturb master branch

**Comment by myselfshivams** [comment]
> @myselfshivams in future please use new branch for creating PR's don't disturb master branch

Hi @himeshparashar,

The reason I created the PR with the master branch was due to the dev branch not being updated, which resulted in conflicts. I apologize for the oversight and will ensure to avoid this in the future by using the appropriate branch.

Thank you for your understanding.

**Comment by myselfshivams** [comment]
@himeshparashar Please add labels, as gssoc will not accept this PR.

**Comment by myselfshivams** [comment]
@himeshparashar Please add labels of level and gssoc so that it can be identified by gssoc

**Pull request merged**
