### PR TITLE
Added Dockerfile, .dockerignore file and the docker-compose.yml file

### PR DESCRIPTION
**Pull request by adityapandey23**
This PR resolves issue number #15 

The demo is added int the issue discussion itself!

### CODE REVIEW

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal can you do a postgres sql instead of mongodb , else looks fine to me update in the pr only

**Comment by adityapandey23** [comment]
Okay on it!
@himeshparashar

**Comment by adityapandey23** [comment]
@Shobhit-Nagpal @himeshparashar 
Done!
Added postgres instead of mongodb
(By mistake I though I have to create a new pr that's why I closed and re-opend it )

**Comment by Shobhit-Nagpal** [comment]
> @Shobhit-Nagpal @himeshparashar Done! Added postgres instead of mongodb (By mistake I though I have to create a new pr that's why I closed and re-opend it )


awesome, i'll just have a look

**Review by Shobhit-Nagpal — COMMENTED** [review]
lgtm @himeshparashar

**Pull request merged**
