### PR TITLE
pop-up for gemini posts with dynamic features

### PR DESCRIPTION
**Pull request by swatified**
here is the demo of what i made for the issue: 

https://github.com/user-attachments/assets/d155bd7d-94b0-480b-a3fe-5482276755c7

**KEY FEATURES I ADDED :**

1. Removed the input field from dashboard
2. Created a pop-up on "Create Posts" button
3. Set up custom prompt for dynamic selection and output from gemini
4.  (Made this painful ui)
5.  Added custom prompts features
6.  Added favourite prompt adding feature (look at the vid)

### CODE REVIEW

**Comment by swatified** [comment]
@himeshparashar @Shobhit-Nagpal @sudhanshutech Have a look and let me know your reviews. This is regarding #54 :)

**Comment by swatified** [comment]
@Shobhit-Nagpal thank youu. Fingers crossed, level 3.

**Comment by swatified** [comment]
@himeshparashar any updates?

**Review by sudhanshutech — COMMENTED** [review]
good move on moving gemini api to lib dir

**Review by sudhanshutech — APPROVED** [review]
looks good to me

**Comment by swatified** [comment]
@sudhanshutech @himeshparashar when can i expect the merge? the program is about to end..

**Comment by swatified** [comment]
@himeshparashar thank you so much for merging it amidst all that. really grateful for that! 🙇

**Comment by himeshparashar** [comment]
@swatified , if you are looking for opportunity, you can send me your resume on LinkedIn, as someone was asking for a developer for a frontend role.

**Comment by swatified** [comment]
sure till when is it open? i might need a day or two to finetune stuff and also its diwali :')

Btwww thank you so much for the opportunity ^^

**Comment by himeshparashar** [comment]
@swatified  assuming till Diwali, have to talk with him about the exact status

**Comment by swatified** [comment]
ok sure gimme a day. mail? @himeshparashar

**Comment by swatified** [comment]
@himeshparashar Hey i have sent you the connection request. Please accept it asap so that I can send you the Resume!

**Pull request merged**
