### PR TITLE
Built Rate us Contact us model ISSUE #70

### LINKED ISSUE #70: Want to add Rating Us functionality
https://github.com/user-attachments/assets/e862337d-9eda-4339-b77e-f94f0bead90c

I want to add a **Rating Us** functionality for this website.
I developed the same thing as you seen on video.

For now it only display a greetings as alert message.
Further you can add a backend functionality to display the ratings in webpage. Though it's an open source project, If i built this functionality, it would be great for you and other also for further improvement in this field.

Please assign me this ISSUE. I want to implement this feature.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
## 📋 Description

Developed 'Contact Us' & 'Rate us' model between accordion & footer section as you seen in the image

## 🔨 Changes Made

image

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #70 

## How should this be tested?

- [x] Test A
- [x] Test B

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### On thing, @himeshparashar  Please give me `label-3` if possible. Because I develop two models along with left side image portion which you tell me to add last night, Also I make this section responsive. So please considered this. Hope you understand. @himeshparashar  Thank you.

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@himeshparashar  please marge this with all labels under `gssoc-extd` and `label-3` 
Please!

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal review needed

**Comment by Suvadip-sana** [comment]
@himeshparashar Please marge after review. It's been long time.

**Comment by sanjay-kv** [comment]
the label admin using was wrong i corrected it

**Comment by Shobhit-Nagpal** [comment]
sure, reviewing

**Comment by Suvadip-sana** [comment]
@Shobhit-Nagpal 
image
image


Here it is. It looks good & professional also in mobile so don't worry about that.
And kindly marge it.

**Review by himeshparashar — APPROVED** [review]
@Suvadip-sana Thanks this looks great

**Pull request merged**
