### PR TITLE
Fix the ISSUE #70 - Add 'Rate us' functionality.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
I fix the ISSUE #70 

Where I built a Full 'Rate Us' Component from scratch.
Here is the demo ---> 

https://github.com/user-attachments/assets/9d139f1a-eceb-4e9f-8cfe-af26621cc611

**Please give me atleast `label-2`**   
Because Initially i raised the issue only for 'rate us' features. But I implement two form as you say.
Please considered this.

@himeshparashar

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@himeshparashar 


Merge this please!

**Review by himeshparashar — CHANGES_REQUESTED** [review]
The "Rate Us" button appears isolated on the side. 

Please take inspiration from this layout: image.

Can you create a design with a form on one side and an illustration on the other? Below the illustration, please include the "Rate Us" functionality. Additionally, position the "Rate Us" button in the right block, just below the email section, to create a more balanced look.

**Comment by Suvadip-sana** [comment]
Didn't understand what you trying to say.  Please elaborate with details. 
I decided in two blocks in this section. In left side the 'get in touch' form is there. On the right side the 'rate us' button is there. 

Now you want this contact details like mobile number, email, place. And under this the rate us button was placed. All this stuff in right side? 

You want same as I told? Or something else.  Please kindly elaborate with proper details @himeshparashar

**Comment by Suvadip-sana** [comment]
@himeshparashar Hey please reply this.

**Comment by himeshparashar** [comment]
@Suvadip-sana 

something like this

image

**Comment by Suvadip-sana** [comment]
@himeshparashar Provide me this image if you want this image on webpage.

**Comment by himeshparashar** [comment]
@Suvadip-sana https://img.freepik.com/free-vector/flat-design-illustration-customer-support_23-2148887720.jpg

you can also refer to any free stock image online that looks good

**Comment by Suvadip-sana** [comment]
@himeshparashar  got it

**Comment by Suvadip-sana** [comment]
rb_2148893296
rb_2148880701
rb_2148886609

rb_2148893295


Among this which one you should try to add? A found this from free version.  Your provided image is good but I think it's color and your website existing color combination should be matched.?

Tell me what you think.
@himeshparashar

**Comment by himeshparashar** [comment]
@Suvadip-sana  

1st 2nd or 5th any looks good to me

**Pull request closed without merging**
