### PR TITLE
Feature/implement a backend for Authorization

### PR DESCRIPTION
**Pull request by BhairabMahanta**
#40 
**Summary**:
In this pull request, I implemented a backend foundation by setting up a PostgreSQL database, along with essential services like JWT authentication, Redis caching, and OTP email verification. Below is a breakdown of what was accomplished:

1. **Error Handling**: 
   - Created three key error-handling files (`ErrorHandler.js`, `catchAsyncError.js`, and `error.js`) to manage errors across the application. This allows for a centralized, consistent error-handling flow and prevents unhandled promise rejections.

2. **Prisma Schema**:
   - Designed the database structure using Prisma and PostgreSQL. I configured environment variables to connect the application to the PostgreSQL instance. Models like `User`, `Profile`, and associated relations were defined.

3. **Environment Variables**:
   - I set up environment variables to safely manage sensitive credentials, such as JWT secrets, Redis connection URL, database URLs, and email service configurations.

4. **JWT Authentication**:
   - JWT access and refresh tokens were implemented for user authentication, enhancing security and scalability for token management.

5. **Redis Connection**:
   - Implemented Redis to manage sessions and OTP caching, improving the efficiency and security of user authentication.
image

6. **Interfaces and Controllers**:
   - Created structured interfaces and controllers to manage user actions, OTP functionality, and email sending, ensuring clean separation of concerns and improving the maintainability of the codebase.

7. **OTP Functionality & Email Sending**:
   - Added functionality for OTP verification and email activation using both Nodemailer and Resend APIs. This helps secure user registration and login processes.

8. **Routes Setup & Testing**:
   - Defined routes for user authentication, email verification, and OTP handling. These were tested using Postman to ensure the backend operates as expected.
image
image
image

**Why This Was Done**:
The project initially lacked a scalable, secure, and efficient backend system and proper error-handling framework. By setting up PostgreSQL and adding the JWT, Redis, and OTP functionalities, I aimed to establish a scalable, secure, and efficient backend system. The newly added features will ensure smooth user onboarding, login, and email verification, improving the overall user experience.

**Request** To review the code @himeshparashar 
---

### CODE REVIEW

**Comment by himeshparashar** [comment]
@BhairabMahanta Great, really loved this. 
But I will review and merge it during the weekend, so please be patient.

**Comment by Shobhit-Nagpal** [comment]
hey @BhairabMahanta, implementations look nice. was curious how you got the idea of using redis

**Comment by BhairabMahanta** [comment]
> hey @BhairabMahanta, implementations look nice. was curious how you got the idea of using redis 

I was looking through some projects using redis, so was curious. So i digged into it and found out that it's for caching users for a two front system! So I implemented it here for caching.

It is only a few lines of codes too, I can remove the requirement of secondary database if you say so.

**Review by himeshparashar — APPROVED** [review]
Thanks for this contribution

**Pull request merged**
