### PR TITLE
Dashboard done

### PR DESCRIPTION
**Pull request by swatified**
Hey, kindly look at the updated dashboard with new ui pull. And let me know if anything else needed before it can be merged. 
Kindly assign me labels if you merge.

https://github.com/user-attachments/assets/c7c87011-e713-4f7d-9690-d142f4a25a35

.env file isnt getting ignored idk whats the issue. please have a look at that. I removed my creds but it may cause issues to other people. something in gitignore i guess.

### CODE REVIEW

**Comment by swatified** [comment]
@himeshparashar @Shobhit-Nagpal have a look onto this. This is regarding #22 by the way.

**Review by himeshparashar — CHANGES_REQUESTED** [review]
### PR Review

#### 1. API Keys Security
Please **change your API keys**, delete the current ones, and use new ones. Once you've done that, ping me to confirm.  
In the future, make sure to use **`.env.local`** for environment variables.

#### 2. Redundant Package Addition
Why was `@clerk/clerk-react` added?  
There's already a Next.js SDK available: `@clerk/clerk-react`. 


#### 3 There's no need to add the following manually in readme.md file:

```bash
npm install @clerk/nextjs@latest @clerk/clerk-react@latest
```

The required dependencies are already listed in the `package.json` file, so simply running:

```bash
npm install
```

is sufficient.
```

**Comment by swatified** [comment]
@himeshparashar  I have done the changes you asked for.  Kindly check out the changes and merge the same. 
P.S. The labels are still not assigned to me. Don't forget to do that before merge. :) working on gemini now.

**Comment by swatified** [comment]
@himeshparashar sirr visit this pr, sirr.

**Pull request merged**
